# Generated by Django 4.1.6 on 2023-12-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0009_remove_report_id_alter_report_reportid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, default=21.9974, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=6, default=79.0011, max_digits=9, null=True),
        ),
    ]
