# Generated by Django 4.1.6 on 2023-12-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0010_alter_report_lat_alter_report_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, default=23.188544, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=6, default=72.628918, max_digits=9, null=True),
        ),
    ]
