# Generated by Django 4.1.6 on 2023-12-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0012_alter_report_lat_alter_report_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='report',
            name='lon',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
